### ISSUE TITLE
Make context menu configurable

### ISSUE THREAD

**Issue by LaserEyess** [woodruffw/ff2mpv#31] opened 2020-09-21 15:48 UTC
Since upgrading to 3.5 I've noticed that when right clicking individual links I need to access an additional context menu to actually play a video. I find this rather annoying, although with the no video option and potentially #20 being merged I do understand why this change was made.

Configuring which options are available to the user so I can just do "right click, play in mpv" would be greatly appreciated.

**Comment by woodruffw** [comment] 2020-09-21 16:48
Thanks for the feedback. This is a dupe of #30, so I'll track it there.

**Closed by woodruffw** 2020-09-21 16:48 UTC
