### ISSUE TITLE
Error: "undefined" on Mac

### ISSUE THREAD

**Issue by ricardopieper** [woodruffw/ff2mpv#17] opened 2019-08-14 02:47 UTC
Hi, I've followed the necessary steps (installed the extension, put the json in the NativeMessagingHosts folder and changed it) but it doesn't work.

I enabled debugging and the only thing that shows up is this "Error: undefined" that happens on line 2.

I attempted to call that line directly like so:

`browser.runtime.sendNativeMessage("ff2mpv", { url: 'https://www.youtube.com/watch?v=Nm5J_9FYU4o' }).then((err) => console.log(err)).catch(err => console.log(err));`

This line successfully catches the error and console.logs it, but it only shows "Error: undefined".

Undefined looks like a javascript error. Any ideas on what I should look for next?

**Comment by ricardopieper** [comment] 2019-08-14 02:50
I'm certain the ff2mpv.py file was not called. I changed it to create some files upon execution but the files never appear. Running it manually works, and it is executable.

**Comment by woodruffw** [comment] 2019-08-14 14:00
Interesting. Could you share your `ff2mpv.json` (i.e., your native messaging config)?

**Comment by ricardopieper** [comment] 2019-08-15 07:51
{
    "name": "ff2mpv",
    "description": "ff2mpv's external manifest",
    "path": "/Users/user/ff2mpv.py",
    "type": "stdio",
    "allowed_extensions": ["ff2mpv@yossarian.net"]
}

**Comment by woodruffw** [comment] 2019-08-15 15:40
Hmm, that looks right to me. Can you confirm that `ff2mpv.py` has the executable bit set?

**Comment by tsurezuregusa** [comment] 2019-08-24 01:04
Greetings. I too am not able to get this working on Mac. Neither the ruby nor the python script works.

Ruby gives this error:
```
stderr output from native app ff2mpv: /Users/user/Library/Application Support/Mozilla/NativeMessagingHosts/ff2mpv:6:in `<main>': undefined method `unpack1' for "5\x00\x00\x00":String (NoMethodError)
stderr output from native app ff2mpv: Did you mean?  unpack
```
```
> ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```


The python script does not run (on my system at least) because python3 is not part of the default install. After changing to `#!/usr/local/bin/python3`, it is clear `/usr/local/bin` is not in the `$PATH` because `mpv` is not found:

```
stderr output from native app ff2mpv: Traceback (most recent call last):
stderr output from native app ff2mpv:   File "/Users/user/ff2mpv.py", line 34, in <module>
stderr output from native app ff2mpv:     main()
stderr output from native app ff2mpv:   File "/Users/user/ff2mpv.py", line 9, in main
stderr output from native app ff2mpv:     Popen(args, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL)
stderr output from native app ff2mpv:   File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
stderr output from native app ff2mpv:     restore_signals, start_new_session)
stderr output from native app ff2mpv:   File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
stderr output from native app ff2mpv:     raise child_exception_type(errno_num, err_msg, err_filename)
stderr output from native app ff2mpv: FileNotFoundError: [Errno 2] No such file or directory: 'mpv': 'mpv'
```
Yet setting the full path, to either `/usr/local/bin/mpv` or the Applications version still does not work. mpv loads but quits immediately, though it seems it is loading the URL according to the outgoing firewall (Little Snitch).

Also, in the process, Firefox had to be added to be able to control the computer under Accessibility in the Security preferences. After that, this error appears, which may or may not be why this is not working.
```
Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for RESP:{ID: org.mozilla.firefox
```
This would seem to imply that Firefox needs to be added to Automation in the Security preferences, but there does not appear to be a way to manually add it. This is something that the system prompts for when a program tries to do something beyond its permissions...

**Comment by woodruffw** [comment] 2019-08-24 01:22
That ruby error looks like a versioning problem -- `unpack1` was added in 2.4.

Thanks for the other additional information, though. I haven't tried the extension on macOS recently, but is was working for me as of a few months ago (without any changes to either Accessibility or Automation). 

I'm not too familiar with Hardened Runtime (I believe it was added in Mojave), but it looks like it requires an additional entitlement from Firefox in order to allow Apple Events to go through. I'm not 100% sure why this is necessary, since `ff2mpv` shouldn't be using Apple Events at all -- it's just `exec`ing `mpv`. Maybe the issue is the `exec`'d process inheriting the entitlement restrictions and MPV requiring events for its own purposes?

**Comment by woodruffw** [comment] 2019-08-24 01:23
Also, marking as a bug due to independent confirmations.

**Comment by ricardopieper** [comment] 2019-09-01 22:08
Hi, sorry for the delay. 

Yes, it was marked as executable. I was able to run it just by typing `./ff2mpv.py`. Is it sufficient?

Other similar projects to this require the user to setup a client, which I believe is a local HTTP server that listens to commands from the browser. It's a bit janky but it works. This is the one I'm using now: https://add0n.com/external-application-button.html

**Comment by woodruffw** [comment] 2019-09-03 12:59
> Yes, it was marked as executable. I was able to run it just by typing `./ff2mpv.py`. Is it sufficient? I even tried using `chmod 777` on i just to see if it would work, but nothing happened.

Yeah, just executable should be sufficient.

> Other similar projects to this require the user to setup a client, which I believe is a local HTTP server that listens to commands from the browser. It's a bit janky but it works.

In *theory* the native messaging API doesn't require a local HTTP server; it *should* just send and receive length-prefixed JSON with a correctly registered client (which is what the `ff2mpv.json` manifest provides). I'm guessing the problem here is some bad interaction between `exec(2)`, `mpv`'s accessibility permissions, and Firefox's default system sandbox profile, but I haven't had any time to test it locally on a Mac. As such it might be resolvable upstream or by making a small change to the way we spawn `mpv`.

**Comment by mrkapqa** [comment] 2019-10-05 17:35
hello , i tried this today following your guide here

https://github.com/woodruffw/ff2mpv/wiki/Installation-on-macOS
(points 1 - 4 and an mpv player  from macports)

the player would not start and when i am executing the 2 script inside terminal i get the following errors

./ff2mpv.py
env: python3: No such file or directory

./ff2mpv.js
./ff2mpv.js: line 1: syntax error near unexpected token `url'
./ff2mpv.js: line 1: `function ff2mpv(url) {'

 ./ff2mpv
(no written output in terminal)


i have changed ff2mpv.json to the ./ff2mpv.py script.

**Comment by woodruffw** [comment] 2019-10-06 15:01
> the player would not start and when i am executing the 2 script inside terminal i get the following errors

You shouldn't be executing these scripts in a terminal; they're designed to be run by the browser.



> i have changed ff2mpv.json to the ./ff2mpv.py script.

This sounds like a potential confusion with the steps -- you shouldn't be renaming any JSON files into Python files. Make sure to copy **either** `ff2mpv` (no suffix) **or** `ff2mpv.py`, **then** copy `ff2mpv.json` to the location in the Wiki page.

**Comment by woodruffw** [comment] 2020-06-12 05:32
Can any of the original reporters confirm that this is still a problem for them? If not, I'm going to close this in a few days.

**Comment by tsurezuregusa** [comment] 2020-06-12 06:14
Greetings, this still does not work for me, now running 10.15.4.

Only `mpv` in the execution path did not seem to do anything. Both setting to `/usr/local/bin/mpv` and `/Applications/...` produced similar results with mpv starting but quitting immediately.

Now there in 10.14 there seems to be `mediaremoted` getting in the way. I am not familiar with this and what it does. It also seems impossible to add Firefox to Automation under Security Preferences, as before.

From the logs it looks like maybe the URL is got getting to mpv ... ?


[1.log](https://github.com/woodruffw/ff2mpv/files/4769080/1.log)
[2.log](https://github.com/woodruffw/ff2mpv/files/4769081/2.log)

**Comment by mrkapqa** [comment] 2020-06-12 07:18
havent used newer MacOS in a while, but hope to test this asap on MacOSX
Mavericks, ElCapitan again with Firefox-ESR, last time it probably didnt
function.

Am 12/06/20 um 08.15 schrieb tsurezuregusa:

**Comment by woodruffw** [comment] 2020-06-12 15:32
Thanks for confirming. I'll try to repro again this evening.

**Comment by mrkapqa** [comment] 2020-06-12 16:07
tried just now with Elcapitan

it would not function with a mpv version of macports and newest youtube-dl (mpv functions fine).
tried with firefox 60esr and latest ff2mpv 3.4


tried both with python and ruby;
path is
/Users/rich/Downloads/ff2mpv-master/ff2mpv
or
/Users/rich/Downloads/ff2mpv-master/ff2mpv.py

/usr/bin/env python3 seems to respond when typed in terminal and it is possible to execute 
ff2mpv (ruby)

but when trying to play video on youtube through rightclick play in ff2mpv no window opens.

**Comment by rw-snaydon** [comment] 2020-08-30 20:40
Hi, not sure if this is helpful, but I thought I'd share.

My OS is Catalina 10.15 and my mpv version is `0.32.0` and was installed with homebrew. To get it to work I had to specify the full path my mpv binary: `/usr/local/bin/mpv`, as @tsurezuregusa also did. Not sure where their issue is coming from but after I did this it worked for me with no issues.

I'd recommend possibly adding this change as a suggestion to the MacOS install instructions (I'd also recommend possibly being more explicit about the fact that it must be an executable by saying "has executable permissions" or "give executable permissions with `chmod +x`", as this was also a hangup for me).

And thanks for your work on this add-on btw, it's really handy :)

**Comment by mrkapqa** [comment] 2020-08-30 22:10
@rw-snaydon where did you specify the full path to mpv binary?
i just tried with latest Firefox and when i open the Add-on Settings for ff2mpv, i cannot seem to find the appropriate section.

**Comment by woodruffw** [comment] 2020-08-30 22:33
Thanks for the additional datapoints, @rw-snaydon! I'll make your recommended changes to the wiki page.

@mrkapqa The path to `mpv` is specified in the native client, which is either the Ruby or Python one, depending on which you installed.

**Comment by woodruffw** [comment] 2020-08-30 22:40
@rw-snaydon Just a follow up question: is `/usr/local/bin` on your `PATH`?

**Comment by mrkapqa** [comment] 2020-08-31 14:30
Hello @woodruffw thank you very much,
do you mean i should edit the "ff2mpv" or "ff2mpv.py"  and include the path to mpv? or would it be the "ff2mpv.js" as per point 3. of the mac-os instructions?
in my case it would be "/opt/local/bin/mpv" as per macports build.

**Comment by woodruffw** [comment] 2020-08-31 14:41
> do you mean i should edit the "ff2mpv" or "ff2mpv.py" and include the path to mpv?

Yep, one of those two, depending on which one you're using. You shouldn't have to make any additional modifications to `ff2mpv.json`.

**Comment by mrkapqa** [comment] 2020-08-31 14:44
Thank you very much,
in `ff2mpv.json` included path to `ff2mpv.py`
and i took a look at it; don§t seem to know where and how to put it.
the first line says
`#!/usr/bin/env python3` and i am not even sure that python3 is installed by default on macOS

**Comment by mrkapqa** [comment] 2020-08-31 14:45
infact, i installed `mpv` via macports with the package `python27`

**Comment by woodruffw** [comment] 2020-08-31 14:53
> and i took a look at it; don§t seem to know where and how to put it.

It doesn't matter where you put `ff2mpv.py` as long as it's executable and the place where you put it is the same path indicated in `ff2mpv.json`.

> and i am not even sure that python3 is installed by default on macOS

You should make sure you're running a relatively recent version of macOS. On 10.15.6, I have `/usr/bin/python3` and that's Python 3.7.3. If you're running an older version of macOS, you should consider using the Ruby native client instead.

**Comment by mrkapqa** [comment] 2020-08-31 15:36
thank you,
infact on mojave 10.14.6 `/usr/bin/python3` gives `-bash: /usr/bin/python3: No such file or directory`

would you please indicate the correct line for `ff2mpv` then
as i am not familiar with this language.

**Comment by mrkapqa** [comment] 2020-08-31 15:42
or now i have python3.7 (macports) in `/opt/local/bin/python3.7` and i could edit the first line in `ff2mpv.py` `/usr/bin/env python3` to match the newly installed python3.7?

**Comment by woodruffw** [comment] 2020-08-31 15:49
Yes, you should be able to change that line to `#!/usr/bin/env python3.7`, assuming that `/opt/local/bin` is on your `PATH`.

**Comment by mrkapqa** [comment] 2020-08-31 15:56
did so accordingly,
now in `ff2mpv.py` first line is set to 
`#!/usr/bin/env python3.7` and set also path to mpv in args `args = ["/opt/local/bin/mpv", "--no-terminal", "--", url]`
but still would not play.
maybe am missing some other important step.

**Comment by mrkapqa** [comment] 2020-08-31 17:12
tried also with `ruby` by using home-brew 
and then
`If you need to have ruby first in your PATH run:
  echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.profile
`
don't know if this is correct as `ff2mpv` (ruby unix-executable?)
has at first line `#!/usr/bin/env ruby`
however, if i evoke this line, nothing happens (terminal stalls)

**Comment by mrkapqa** [comment] 2020-08-31 17:24
@woodruffw thank you very much, your workaround hosted here
https://github.com/woodruffw/ff2mpv/issues/13
when adapted to macports-python3 ("/opt/local/bin/python3.7" instead of "/usr/local/bin/python3") and mpv from macports ("/opt/local/bin/mpv) functions beautifully on my mac running mojave 10.14.6; finally got this running, as on linux and windows there seem no problems getting this to function.

**Comment by woodruffw** [comment] 2020-08-31 17:25
Gotcha, good to know. I'm gonna go ahead and close this then, since it's mitigated by the same fix in #13.

**Closed by woodruffw** 2020-08-31 17:25 UTC
Labels: P:macos, bug, needs information

**Comment by mrkapqa** [comment] 2020-08-31 18:35
very nice, now can use ff2mpv + svp4mac combo (mpv+vaporsynth@ 60fps or so, via home-brew)

**Comment by mrkapqa** [comment] 2020-09-05 12:37
just tried on Mac OS X Mavericks,


can confirm that the ff2mpv.py included in the .zip is not functional, however the postet workaround by you functions.

have installed mpv via macports (first installed python27)
then installed python37 and adapted the ff2mpv.py accordingly.

in my case it looks then like this here

`#!/opt/local/bin/python3.7

import sys, struct, json, os
from subprocess import Popen, DEVNULL

def main():
    message = get_message()
    url = message.get('url')
    args = ['/opt/local/bin/mpv', url]
    env = os.environ.copy()
    env["PATH"] = f"{env['PATH']}:/usr/local/bin"
    Popen(args, stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL, env=env)
    # Need to respond something to avoid "Error: An unexpected error occurred"
    # in Browser Console.
    send_message('ok')


# https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#App_side
def get_message():
    raw_length = sys.stdin.buffer.read(4)
    if not raw_length:
        return {}
    length = struct.unpack('@I', raw_length)[0]
    message = sys.stdin.buffer.read(length).decode('utf-8')
    return json.loads(message)


def send_message(message):
    content = json.dumps(message).encode('utf-8')
    length = struct.pack('@I', len(content))
    sys.stdout.buffer.write(length)
    sys.stdout.buffer.write(content)
    sys.stdout.buffer.flush()


if __name__ == '__main__':
    main()
`
